name: Build Push Sign
on: { push: { branches: ['main'] } }

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Login to GitHub
        uses: docker/login-action@v1.9.0
        with:
          registry: wepatestacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - uses: sigstore/cosign-installer@main

      - name: Sign the images
        run: |
          cosign sign wepatestacr.azurecr.io/nginx:latest --force
        env:
          COSIGN_EXPERIMENTAL: 1

      - name: Verify the images
        run: |
          cosign verify wepatestacr.azurecr.io/nginx:latest
        env:
          COSIGN_EXPERIMENTAL: 1
